name: CI/CD Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PROJECT_GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        export dockerimg_name=ghcr.io/varunshaji98/investsavvy-$(date +%s)
        docker build . --file backend/Dockerfile --tag $dockerimg_name
    - name: Do a quick sanity test on the docker image
      run: |
        docker run -p 3000:3000 \
          -e DB_HOST=${{ secrets.DB_HOST }} \
          -e DB_PORT=${{ secrets.DB_PORT }} \
          -e DB_USER=${{ secrets.DB_USER }} \
          -e DB_PASS=${{ secrets.DB_PASS }} \
          -e DB_NAME=${{ secrets.DB_NAME }} \
          -d $dockerimg_name
    - name: Push to Github Container Registry
      run: docker push $dockerimg_name